---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Julian Schneider
-- Authors: Julian Schneider
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- Register map of the MIB: addresses, field positions and reset values of the AXI4-Lite registers.
-- Generated by tools/regmap.py from hdl/ofb_mib/regs/ofb_regs.yml, do not edit.
--
-- Documentation: hdl/ofb_mib/docs/register_map.md

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;

---------------------------------------------------------------------------------------------------
-- Package Header
---------------------------------------------------------------------------------------------------
package ofb_regs_pkg is

    -----------------------------------------------------------------------------------------------
    -- Identification
    -----------------------------------------------------------------------------------------------
    constant RegMapId_c : std_logic_vector(31 downto 0) := x"0FB10006";

    -----------------------------------------------------------------------------------------------
    -- Register addresses (byte addresses)
    -----------------------------------------------------------------------------------------------
    constant RegId_c               : natural := 16#000#;
    constant RegGenerics_c         : natural := 16#004#;
    constant RegDlCtrl_c           : natural := 16#008#;
    constant RegDlBcInterval_c     : natural := 16#00C#;
    constant RegDlStatus_c         : natural := 16#010#;
    constant RegDlErrors_c         : natural := 16#014#;
    constant RegDlRetries_c        : natural := 16#018#;
    constant RegDlCrc16Count_c     : natural := 16#01C#;
    constant RegDlCrc8Count_c      : natural := 16#020#;
    constant RegDlFrameCount_c     : natural := 16#024#;
    constant RegDlSeqCount_c       : natural := 16#028#;
    constant RegVcHasCredit_c      : natural := 16#030#;
    constant RegVcInputOverflow_c  : natural := 16#034#;
    constant RegVcCreditOverflow_c : natural := 16#038#;
    constant RegVcFramingError_c   : natural := 16#03C#;
    constant RegMlStatus_c         : natural := 16#040#;
    constant RegIrqMask_c          : natural := 16#044#;
    constant RegVcBwOver_c         : natural := 16#048#;
    constant RegVcBwUnder_c        : natural := 16#04C#;
    constant RegVcIdleLimit_c      : natural := 16#050#;
    constant RegSchedStatus_c      : natural := 16#054#;
    constant RegMlCtrl_c           : natural := 16#058#;
    constant RegMlMisaligned_c     : natural := 16#05C#;
    constant RegEccStatus_c        : natural := 16#060#;
    constant RegEccSelect_c        : natural := 16#064#;
    constant RegEccCount_c         : natural := 16#068#;
    constant RegEccInject_c        : natural := 16#06C#;

    -----------------------------------------------------------------------------------------------
    -- LANE registers: address of instance n = Reg<Name>_c + n * RegLaneStride_c
    -----------------------------------------------------------------------------------------------
    constant RegLaneBase_c            : natural := 16#100#;
    constant RegLaneStride_c          : natural := 16#020#;
    constant RegLaneCtrl_c            : natural := 16#100#;
    constant RegLaneStatus_c          : natural := 16#104#;
    constant RegLaneEvents_c          : natural := 16#108#;
    constant RegLaneReasons_c         : natural := 16#10C#;
    constant RegLaneTimeoutCount_c    : natural := 16#110#;
    constant RegLanePrbsCtrl_c        : natural := 16#114#;
    constant RegLanePrbsErrors_c      : natural := 16#118#;
    constant RegLanePrbsWords_c       : natural := 16#11C#;
    constant RegLaneCtrlOfs_c         : natural := 16#00#;
    constant RegLaneStatusOfs_c       : natural := 16#04#;
    constant RegLaneEventsOfs_c       : natural := 16#08#;
    constant RegLaneReasonsOfs_c      : natural := 16#0C#;
    constant RegLaneTimeoutCountOfs_c : natural := 16#10#;
    constant RegLanePrbsCtrlOfs_c     : natural := 16#14#;
    constant RegLanePrbsErrorsOfs_c   : natural := 16#18#;
    constant RegLanePrbsWordsOfs_c    : natural := 16#1C#;

    -----------------------------------------------------------------------------------------------
    -- VC registers: address of instance n = Reg<Name>_c + n * RegVcStride_c
    -----------------------------------------------------------------------------------------------
    constant RegVcBase_c         : natural := 16#400#;
    constant RegVcStride_c       : natural := 16#010#;
    constant RegVcCfg_c          : natural := 16#400#;
    constant RegVcBandwidth_c    : natural := 16#404#;
    constant RegVcSlotsLo_c      : natural := 16#408#;
    constant RegVcSlotsHi_c      : natural := 16#40C#;
    constant RegVcCfgOfs_c       : natural := 16#00#;
    constant RegVcBandwidthOfs_c : natural := 16#04#;
    constant RegVcSlotsLoOfs_c   : natural := 16#08#;
    constant RegVcSlotsHiOfs_c   : natural := 16#0C#;

    -----------------------------------------------------------------------------------------------
    -- Fields: bit of a one-bit field, lowest and highest bit of a wider field
    -----------------------------------------------------------------------------------------------

    constant IdIdLo_c : natural := 0;
    constant IdIdHi_c : natural := 31;

    constant GenericsNumVcLo_c    : natural := 0;
    constant GenericsNumVcHi_c    : natural := 7;
    constant GenericsNumLanesLo_c : natural := 8;
    constant GenericsNumLanesHi_c : natural := 11;

    constant DlCtrlLinkReset_c      : natural := 0;
    constant DlCtrlInterfaceReset_c : natural := 1;
    constant DlCtrlDataScrambled_c  : natural := 8;

    constant DlBcIntervalIntervalLo_c : natural := 0;
    constant DlBcIntervalIntervalHi_c : natural := 15;

    constant DlStatusLinkStateLo_c   : natural := 0;
    constant DlStatusLinkStateHi_c   : natural := 1;
    constant DlStatusRxErrStateLo_c  : natural := 2;
    constant DlStatusRxErrStateHi_c  : natural := 3;
    constant DlStatusWordIdStateLo_c : natural := 4;
    constant DlStatusWordIdStateHi_c : natural := 6;
    constant DlStatusErbEmpty_c      : natural := 8;

    constant DlErrorsCrc16_c           : natural := 0;
    constant DlErrorsCrc8_c            : natural := 1;
    constant DlErrorsFrame_c           : natural := 2;
    constant DlErrorsSequence_c        : natural := 3;
    constant DlErrorsProtocol_c        : natural := 4;
    constant DlErrorsFarEndLinkReset_c : natural := 5;
    constant DlErrorsBcDiscard_c       : natural := 6;
    constant DlErrorsInputOverflow_c   : natural := 7;
    constant DlErrorsCreditOverflow_c  : natural := 8;
    constant DlErrorsFramingError_c    : natural := 9;
    constant DlErrorsRxRowOverflow_c   : natural := 10;

    constant DlRetriesCountLo_c : natural := 0;
    constant DlRetriesCountHi_c : natural := 31;

    constant DlCrc16CountCountLo_c : natural := 0;
    constant DlCrc16CountCountHi_c : natural := 15;

    constant DlCrc8CountCountLo_c : natural := 0;
    constant DlCrc8CountCountHi_c : natural := 15;

    constant DlFrameCountCountLo_c : natural := 0;
    constant DlFrameCountCountHi_c : natural := 15;

    constant DlSeqCountCountLo_c : natural := 0;
    constant DlSeqCountCountHi_c : natural := 15;

    constant VcHasCreditVcLo_c : natural := 0;

    constant VcInputOverflowVcLo_c : natural := 0;

    constant VcCreditOverflowVcLo_c : natural := 0;

    constant VcFramingErrorVcLo_c : natural := 0;

    constant MlStatusDataSendingLo_c   : natural := 0;
    constant MlStatusDataSendingHi_c   : natural := 3;
    constant MlStatusDataReceivingLo_c : natural := 4;
    constant MlStatusDataReceivingHi_c : natural := 7;
    constant MlStatusAlignStateLo_c    : natural := 8;
    constant MlStatusAlignStateHi_c    : natural := 9;
    constant MlStatusBypass_c          : natural := 10;

    constant IrqMaskDlErrorsLo_c   : natural := 0;
    constant IrqMaskDlErrorsHi_c   : natural := 10;
    constant IrqMaskLaneEventsLo_c : natural := 16;
    constant IrqMaskLaneEventsHi_c : natural := 19;
    constant IrqMaskEccDed_c       : natural := 24;
    constant IrqMaskEccSec_c       : natural := 25;

    constant VcBwOverVcLo_c : natural := 0;

    constant VcBwUnderVcLo_c : natural := 0;

    constant VcIdleLimitLimitLo_c : natural := 0;
    constant VcIdleLimitLimitHi_c : natural := 31;

    constant SchedStatusTimeSlotLo_c : natural := 0;
    constant SchedStatusTimeSlotHi_c : natural := 5;

    constant MlCtrlMaxDataLanesLo_c : natural := 0;
    constant MlCtrlMaxDataLanesHi_c : natural := 2;
    constant MlCtrlBypass_c         : natural := 8;

    constant MlMisalignedCountLo_c : natural := 0;
    constant MlMisalignedCountHi_c : natural := 15;

    constant EccStatusDedLo_c : natural := 0;
    constant EccStatusDedHi_c : natural := 8;
    constant EccStatusSec_c   : natural := 16;

    constant EccSelectChannelLo_c : natural := 0;
    constant EccSelectChannelHi_c : natural := 3;

    constant EccCountSecCountLo_c : natural := 0;
    constant EccCountSecCountHi_c : natural := 15;
    constant EccCountDedCountLo_c : natural := 16;
    constant EccCountDedCountHi_c : natural := 31;

    constant EccInjectChannelLo_c : natural := 0;
    constant EccInjectChannelHi_c : natural := 3;
    constant EccInjectDouble_c    : natural := 8;

    constant LaneCtrlLaneStart_c          : natural := 0;
    constant LaneCtrlAutoStart_c          : natural := 1;
    constant LaneCtrlLaneReset_c          : natural := 2;
    constant LaneCtrlNearLoopback_c       : natural := 3;
    constant LaneCtrlFarLoopback_c        : natural := 4;
    constant LaneCtrlTxEn_c               : natural := 5;
    constant LaneCtrlRxEn_c               : natural := 6;
    constant LaneCtrlStandbyReasonLo_c    : natural := 8;
    constant LaneCtrlStandbyReasonHi_c    : natural := 15;
    constant LaneCtrlSerialNearLoopback_c : natural := 16;
    constant LaneCtrlSerialFarLoopback_c  : natural := 17;

    constant LaneStatusStateLo_c         : natural := 0;
    constant LaneStatusStateHi_c         : natural := 3;
    constant LaneStatusRxPolarity_c      : natural := 4;
    constant LaneStatusNoSignal_c        : natural := 5;
    constant LaneStatusBitSync_c         : natural := 6;
    constant LaneStatusPrbsLocked_c      : natural := 7;
    constant LaneStatusRxerrCountLo_c    : natural := 8;
    constant LaneStatusRxerrCountHi_c    : natural := 15;
    constant LaneStatusFarCapabilityLo_c : natural := 16;
    constant LaneStatusFarCapabilityHi_c : natural := 23;

    constant LaneEventsRxerrOverflow_c : natural := 0;
    constant LaneEventsTimeout_c       : natural := 1;
    constant LaneEventsFarStandby_c    : natural := 2;
    constant LaneEventsFarLostSignal_c : natural := 3;

    constant LaneReasonsStandbyReasonLo_c    : natural := 0;
    constant LaneReasonsStandbyReasonHi_c    : natural := 7;
    constant LaneReasonsLostSignalReasonLo_c : natural := 8;
    constant LaneReasonsLostSignalReasonHi_c : natural := 15;

    constant LaneTimeoutCountCountLo_c : natural := 0;
    constant LaneTimeoutCountCountHi_c : natural := 15;

    constant LanePrbsCtrlTxPatternLo_c : natural := 0;
    constant LanePrbsCtrlTxPatternHi_c : natural := 3;
    constant LanePrbsCtrlRxPatternLo_c : natural := 4;
    constant LanePrbsCtrlRxPatternHi_c : natural := 7;
    constant LanePrbsCtrlHold_c        : natural := 8;
    constant LanePrbsCtrlCountReset_c  : natural := 16;
    constant LanePrbsCtrlForceError_c  : natural := 17;

    constant LanePrbsErrorsCountLo_c : natural := 0;
    constant LanePrbsErrorsCountHi_c : natural := 31;

    constant LanePrbsWordsCountLo_c : natural := 0;
    constant LanePrbsWordsCountHi_c : natural := 31;

    constant VcCfgPriorityLo_c : natural := 0;
    constant VcCfgPriorityHi_c : natural := 3;
    constant VcCfgContinuous_c : natural := 8;
    constant VcCfgVnLo_c       : natural := 16;
    constant VcCfgVnHi_c       : natural := 21;

    constant VcBandwidthFactorLo_c : natural := 0;
    constant VcBandwidthFactorHi_c : natural := 15;

    constant VcSlotsLoSlotsLo_c : natural := 0;
    constant VcSlotsLoSlotsHi_c : natural := 31;

    constant VcSlotsHiSlotsLo_c : natural := 0;
    constant VcSlotsHiSlotsHi_c : natural := 31;

    -----------------------------------------------------------------------------------------------
    -- Reset values of the registers whose fields all have a fixed reset value
    -----------------------------------------------------------------------------------------------
    constant RegDlCtrlReset_c           : std_logic_vector(31 downto 0) := x"00000100";
    constant RegDlBcIntervalReset_c     : std_logic_vector(31 downto 0) := x"00000028";
    constant RegDlErrorsReset_c         : std_logic_vector(31 downto 0) := x"00000000";
    constant RegDlRetriesReset_c        : std_logic_vector(31 downto 0) := x"00000000";
    constant RegDlCrc16CountReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegDlCrc8CountReset_c      : std_logic_vector(31 downto 0) := x"00000000";
    constant RegDlFrameCountReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegDlSeqCountReset_c       : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIrqMaskReset_c          : std_logic_vector(31 downto 0) := x"00000000";
    constant RegVcIdleLimitReset_c      : std_logic_vector(31 downto 0) := x"0002625A";
    constant RegMlMisalignedReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccStatusReset_c        : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccSelectReset_c        : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccCountReset_c         : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccInjectReset_c        : std_logic_vector(31 downto 0) := x"00000000";
    constant RegLaneCtrlReset_c         : std_logic_vector(31 downto 0) := x"00000062";
    constant RegLaneEventsReset_c       : std_logic_vector(31 downto 0) := x"00000000";
    constant RegLaneTimeoutCountReset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegLanePrbsCtrlReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegVcSlotsLoReset_c        : std_logic_vector(31 downto 0) := x"FFFFFFFF";
    constant RegVcSlotsHiReset_c        : std_logic_vector(31 downto 0) := x"FFFFFFFF";

end package;
